name: Trigger Jenkins Job

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@master
        with:
          jenkins_url: "http://http://localhost:8080/"
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "nodejs_project"
